In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('vegas.txt')

In [3]:
df

,Date,Location,Team,OppTeam,TeamId,GameId,PercentBet_ML,Open_Line_ML,Pinnacle_ML,5dimes_ML,...,Average_Line_OU,Average_Odds_OU,Best_Line_OU,Worst_Line_OU,Best_Odds_OU,Worst_Odds_OU,Pts,Spread,Result,Total
0,2018-10-16,away,Philadelphia,Boston,1610612755,21800001,46.0,172.0,181.0,185.0,...,210.92,-106.17,212.0,208.5,-102.0,-110.0,87,-18,L,192
1,2018-10-16,home,Boston,Philadelphia,1610612738,21800001,54.0,-205.0,-202.0,-200.0,...,210.92,-108.83,212.0,208.5,-105.0,-115.0,105,18,W,192
2,2018-10-16,away,Oklahoma City,Golden State,1610612760,21800002,55.7,664.0,768.0,725.0,...,220.83,-108.33,223.5,220.0,-105.0,-115.0,100,-8,L,208
3,2018-10-16,home,Golden State,Oklahoma City,1610612744,21800002,44.3,-1000.0,-1002.0,-925.0,...,220.83,-106.67,223.5,220.0,-105.0,-110.0,108,8,W,208
4,2018-10-17,away,Milwaukee,Charlotte,1610612749,21800003,58.9,-130.0,-160.0,-155.0,...,221.08,-108.67,222.5,217.0,-104.0,-115.0,113,1,W,225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,2019-04-10,home,Denver,Minnesota,1610612743,21801228,45.2,-900.0,-794.0,-830.0,...,218.42,-107.17,218.5,218.0,-105.0,-110.0,99,4,W,194
2448,2019-04-10,away,Utah,L.A. Clippers,1610612762,21801229,61.6,199.0,249.0,275.0,...,225.50,-107.40,226.0,225.0,-102.0,-115.0,137,-6,L,280
2449,2019-04-10,home,L.A. Clippers,Utah,1610612746,21801229,38.4,-240.0,-281.0,-305.0,...,225.50,-106.60,226.0,225.0,-105.0,-110.0,143,6,W,280
2450,2019-04-10,away,Sacramento,Portland,1610612758,21801230,58.1,317.0,135.0,135.0,...,227.00,-107.67,229.0,226.5,-105.0,-111.0,131,-5,L,267
2451,2019-04-10,home,Portland,Sacramento,1610612757,21801230,41.9,-400.0,-149.0,-145.0,...,227.00,-107.33,229.0,226.5,-100.0,-115.0,136,5,W,267

In [4]:
i = 0
for col in df.columns:
    print(col, i)
    i += 1

Date 0
Location 1
Team 2
OppTeam 3
TeamId 4
GameId 5
PercentBet_ML 6
Open_Line_ML 7
Pinnacle_ML 8
5dimes_ML 9
Heritage_ML 10
Bovada_ML 11
Betonline_ML 12
Average_Line_ML 13
Best_Line_ML 14
Worst_Line_ML 15
PercentBet_Spread 16
Open_Line_Spread 17
Open_Odds_Spread 18
Pinnacle_Line_Spread 19
Pinnacle_Odds_Spread 20
5dimes_Line_Spread 21
5dimes_Odds_Spread 22
Heritage_Line_Spread 23
Heritage_Odds_Spread 24
Bovada_Line_Spread 25
Bovada_Odds_Spread 26
Betonline_Line_Spread 27
Betonline_Odds_Spread 28
Average_Line_Spread 29
Average_Odds_Spread 30
Best_Line_Spread 31
Worst_Line_Spread 32
Best_Odds_Spread 33
Worst_Odds_Spread 34
PercentBet_OU 35
Open_Line_OU 36
Open_Odds_OU 37
Pinnacle_Line_OU 38
Pinnacle_Odds_OU 39
5dimes_Line_OU 40
5dimes_Odds_OU 41
Heritage_Line_OU 42
Heritage_Odds_OU 43
Bovada_Line_OU 44
Bovada_Odds_OU 45
Betonline_Line_OU 46
Betonline_Odds_OU 47
Average_Line_OU 48
Average_Odds_OU 49
Best_Line_OU 50
Worst_Line_OU 51
Best_Odds_OU 52
Worst_Odds_OU 53
Pts 54
Spread 55
Result 56
Total 57

In [5]:
df.iloc[:,6:15]

,PercentBet_ML,Open_Line_ML,Pinnacle_ML,5dimes_ML,Heritage_ML,Bovada_ML,Betonline_ML,Average_Line_ML,Best_Line_ML
0,46.0,172.0,181.0,185.0,180.0,190.0,180.0,183.2,190.0
1,54.0,-205.0,-202.0,-200.0,-210.0,-230.0,-210.0,-210.4,-200.0
2,55.7,664.0,768.0,725.0,600.0,650.0,825.0,713.6,825.0
3,44.3,-1000.0,-1002.0,-925.0,-850.0,-1100.0,-1200.0,-1015.4,-850.0
4,58.9,-130.0,-160.0,-155.0,-160.0,-170.0,-165.0,-162.0,-155.0
...,...,...,...,...,...,...,...,...,...
2447,45.2,-900.0,-794.0,-830.0,-920.0,-1000.0,-900.0,-888.8,-794.0
2448,61.6,199.0,249.0,275.0,270.0,270.0,250.0,262.8,275.0
2449,38.4,-240.0,-281.0,-305.0,-330.0,-340.0,-300.0,-311.2,-281.0
2450,58.1,317.0,135.0,135.0,130.0,130.0,125.0,131.0,135.0
2451,41.9,-400.0,-149.0,-145.0,-150.0,-150.0,-145.0,-147.8,-145.0

In [6]:
play = df.copy()

In [7]:
play = play[['Date','Location','Team','OppTeam','TeamId','GameId','PercentBet_ML','Average_Line_ML','PercentBet_Spread','Average_Line_Spread','Average_Odds_Spread','PercentBet_OU','Average_Line_OU','Average_Odds_OU','Pts','Spread','Result','Total']]

In [8]:
play

,Date,Location,Team,OppTeam,TeamId,GameId,PercentBet_ML,Average_Line_ML,PercentBet_Spread,Average_Line_Spread,Average_Odds_Spread,PercentBet_OU,Average_Line_OU,Average_Odds_OU,Pts,Spread,Result,Total
0,2018-10-16,away,Philadelphia,Boston,1610612755,21800001,46.0,183.2,45.1,4.70,-105.80,56.9,210.92,-106.17,87,-18,L,192
1,2018-10-16,home,Boston,Philadelphia,1610612738,21800001,54.0,-210.4,54.9,-4.70,-108.20,43.1,210.92,-108.83,105,18,W,192
2,2018-10-16,away,Oklahoma City,Golden State,1610612760,21800002,55.7,713.6,42.4,12.50,-106.00,52.2,220.83,-108.33,100,-8,L,208
3,2018-10-16,home,Golden State,Oklahoma City,1610612744,21800002,44.3,-1015.4,57.6,-12.50,-109.83,47.8,220.83,-106.67,108,8,W,208
4,2018-10-17,away,Milwaukee,Charlotte,1610612749,21800003,58.9,-162.0,58.6,-3.50,-109.40,56.7,221.08,-108.67,113,1,W,225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,2019-04-10,home,Denver,Minnesota,1610612743,21801228,45.2,-888.8,59.6,-12.67,-107.67,43.8,218.42,-107.17,99,4,W,194
2448,2019-04-10,away,Utah,L.A. Clippers,1610612762,21801229,61.6,262.8,39.7,7.33,-108.67,46.5,225.50,-107.40,137,-6,L,280
2449,2019-04-10,home,L.A. Clippers,Utah,1610612746,21801229,38.4,-311.2,60.3,-7.33,-110.17,53.5,225.50,-106.60,143,6,W,280
2450,2019-04-10,away,Sacramento,Portland,1610612758,21801230,58.1,131.0,58.3,3.67,-107.50,55.7,227.00,-107.67,131,-5,L,267
2451,2019-04-10,home,Portland,Sacramento,1610612757,21801230,41.9,-147.8,41.7,-3.67,-107.50,44.3,227.00,-107.33,136,5,W,267

In [9]:
play.dtypes

Date                    object
Location                object
Team                    object
OppTeam                 object
TeamId                   int64
GameId                   int64
PercentBet_ML          float64
Average_Line_ML        float64
PercentBet_Spread      float64
Average_Line_Spread    float64
Average_Odds_Spread    float64
PercentBet_OU          float64
Average_Line_OU        float64
Average_Odds_OU        float64
Pts                      int64
Spread                   int64
Result                  object
Total                    int64
dtype: object

In [10]:
num_rows = len(play.index)
num_cols = len(play.columns)

In [11]:
spread_wl = []

for i in np.arange(num_rows):
    given_spread = play.iloc[i,9]
    team_pts = play.iloc[i,14]
    tot_pts = play.iloc[i,17]
    opp_pts = tot_pts - team_pts
    
    if (given_spread + team_pts) > opp_pts:
        spread_wl.append(1)
    else:
        spread_wl.append(0)

In [12]:
OU_wl = []

for i in np.arange(num_rows):
    given_OU = play.iloc[i,12]
    actual_OU = play.iloc[i,17]
    
    if (actual_OU > given_OU):
        OU_wl.append(1)
    else:
        OU_wl.append(0)

In [13]:
ml_wl = []

for i in np.arange(num_rows):
    result = play.iloc[i,16]
    
    if result == 'W':
        ml_wl.append(1)
    else:
        ml_wl.append(0)

In [14]:
play['Spread WL'] = spread_wl
play['Over/Under WL'] = OU_wl
play['MoneyLine WL'] = ml_wl
play

,Date,Location,Team,OppTeam,TeamId,GameId,PercentBet_ML,Average_Line_ML,PercentBet_Spread,Average_Line_Spread,...,PercentBet_OU,Average_Line_OU,Average_Odds_OU,Pts,Spread,Result,Total,Spread WL,Over/Under WL,MoneyLine WL
0,2018-10-16,away,Philadelphia,Boston,1610612755,21800001,46.0,183.2,45.1,4.70,...,56.9,210.92,-106.17,87,-18,L,192,0,0,0
1,2018-10-16,home,Boston,Philadelphia,1610612738,21800001,54.0,-210.4,54.9,-4.70,...,43.1,210.92,-108.83,105,18,W,192,1,0,1
2,2018-10-16,away,Oklahoma City,Golden State,1610612760,21800002,55.7,713.6,42.4,12.50,...,52.2,220.83,-108.33,100,-8,L,208,1,0,0
3,2018-10-16,home,Golden State,Oklahoma City,1610612744,21800002,44.3,-1015.4,57.6,-12.50,...,47.8,220.83,-106.67,108,8,W,208,0,0,1
4,2018-10-17,away,Milwaukee,Charlotte,1610612749,21800003,58.9,-162.0,58.6,-3.50,...,56.7,221.08,-108.67,113,1,W,225,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,2019-04-10,home,Denver,Minnesota,1610612743,21801228,45.2,-888.8,59.6,-12.67,...,43.8,218.42,-107.17,99,4,W,194,0,0,1
2448,2019-04-10,away,Utah,L.A. Clippers,1610612762,21801229,61.6,262.8,39.7,7.33,...,46.5,225.50,-107.40,137,-6,L,280,1,1,0
2449,2019-04-10,home,L.A. Clippers,Utah,1610612746,21801229,38.4,-311.2,60.3,-7.33,...,53.5,225.50,-106.60,143,6,W,280,0,1,1
2450,2019-04-10,away,Sacramento,Portland,1610612758,21801230,58.1,131.0,58.3,3.67,...,55.7,227.00,-107.67,131,-5,L,267,0,1,0
2451,2019-04-10,home,Portland,Sacramento,1610612757,21801230,41.9,-147.8,41.7,-3.67,...,44.3,227.00,-107.33,136,5,W,267,1,1,1